name: Linting Workflow

on:
  push:
    branches: [ "develop", "feature/linting-workflow" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm install

      - name: Run HTMLHint
        run: npx htmlhint "**/*.html"

      - name: Run Stylelint
        run: npx stylelint "**/*.css"
